### ISSUE TITLE
Error in co-ordinate defining

### ISSUE THREAD

**Issue by sumitawinash** [htso/Coronavirus_Epidemic#1]
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  object 'new.cases' not found

**Comment by htso** [comment]
which script did you run to get that error, and on what data ?

**Comment by aditikumar-png** [comment]
getting error on the data of nCoV.R
![error](https://user-images.githubusercontent.com/61941080/79316044-6ac27a80-7f21-11ea-81c3-271db8595e29.JPG)

**Comment by sumitawinash** [comment]
> which script did you run to get that error, and on what data ?

I am running coronavirus.R and it uses nCoV.RData

**Comment by htso** [comment]
Hi, pls try again. The data file in repo has data beyond Feb 11, which is the cut off point after which I didn't maintain. I added few lines in coronavirus.R to create the variables needed for the plot.

Let me know if you find other issues.
